name: test-actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    name: test something

    steps:
    - name: Set Date
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        date=$(date +%Y-%m-%d)
        echo "DATE=$date" >> $GITHUB_ENV

    - name: get something
      run: |
        wget https://texer.cn/config.tar.gz

    - name: upload test file
      uses: actions/upload-artifact@main
      with:
        name: ${{env.DATE}}_test_config.tar.gz
        path: |
          *.tar.gz
